version: '3.3'
services:
  accountmanager-app:
   image: accountmanager-app
   build: accountmanager/
   restart: always
   network_mode: host
   ports:
     - 9001:9001
   expose:
     - 9001
   depends_on:
     - gipher-mysql
  giphermanager-app:
   image: giphermanager-app
   build: giphermanager/
   restart: always
   network_mode: host
   ports:
     - 9002:9002
   expose:
     - 9002
   depends_on:
     - gipher-mysql

  gipher-mysql:
   image: mysql
   network_mode: host
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: gipherdb
     MYSQL_USER: gipheruser
     MYSQL_PASSWORD: gipherpwd
   volumes:
     - /opt/gipher/mysqldb:/var/lib/mysql
  angular:
    image: angular-app
    build: GipherUI
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
